# Form implementation generated from reading ui file 'ui/import_from_folder.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_import_from_folder(object):
    def setupUi(self, import_from_folder):
        import_from_folder.setObjectName("import_from_folder")
        import_from_folder.resize(372, 326)
        import_from_folder.setWindowTitle("Arc NeuroWave Visualizer")
        self.centralwidget = QtWidgets.QWidget(parent=import_from_folder)
        self.centralwidget.setObjectName("centralwidget")
        self.label_path = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(10, 10, 71, 26))
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(90, 10, 191, 26))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.pushButton_browse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(290, 10, 75, 26))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.textEdit_log = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 70, 351, 241))
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 40, 75, 24))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        import_from_folder.setCentralWidget(self.centralwidget)

        self.retranslateUi(import_from_folder)
        QtCore.QMetaObject.connectSlotsByName(import_from_folder)

    def retranslateUi(self, import_from_folder):
        _translate = QtCore.QCoreApplication.translate
        self.label_path.setText(_translate("import_from_folder", "Porject Path"))
        self.pushButton_browse.setText(_translate("import_from_folder", "Browse"))
        self.pushButton.setText(_translate("import_from_folder", "OK"))
