# Form implementation generated from reading ui file 'ui/import_settings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_import_settings(object):
    def setupUi(self, import_settings):
        import_settings.setObjectName("import_settings")
        import_settings.resize(372, 300)
        import_settings.setWindowTitle("Arc NeuroWave Visualizer")
        self.centralwidget = QtWidgets.QWidget(parent=import_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.label_path = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(10, 10, 71, 26))
        self.label_path.setObjectName("label_path")
        self.lineEdit_path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_path.setGeometry(QtCore.QRect(90, 10, 191, 26))
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.pushButton_browse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(290, 10, 75, 26))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 50, 191, 26))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 26))
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 26))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 90, 191, 26))
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("Select a sample rate...")
        self.comboBox.setMaxVisibleItems(9)
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 90, 75, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 50, 75, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit_log = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 130, 351, 140))
        self.textEdit_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        import_settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(import_settings)
        QtCore.QMetaObject.connectSlotsByName(import_settings)

    def retranslateUi(self, import_settings):
        _translate = QtCore.QCoreApplication.translate
        self.label_path.setText(_translate("import_settings", "Data Path"))
        self.pushButton_browse.setText(_translate("import_settings", "Browse"))
        self.comboBox_2.setCurrentText(_translate("import_settings", "Select a data type..."))
        self.label.setText(_translate("import_settings", "Data Type"))
        self.label_2.setText(_translate("import_settings", "Sample rate"))
        self.pushButton.setText(_translate("import_settings", "OK"))
        self.pushButton_2.setText(_translate("import_settings", "Cancel"))
