# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcNeuroViz(object):
    def setupUi(self, ArcNeuroViz):
        ArcNeuroViz.setObjectName("ArcNeuroViz")
        ArcNeuroViz.resize(960, 720)
        self.menubar = QtWidgets.QMenuBar(parent=ArcNeuroViz)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.BrainWidget = QVTKRenderWindowInteractor(parent=ArcNeuroViz)
        self.BrainWidget.setEnabled(True)
        self.BrainWidget.setGeometry(QtCore.QRect(305, 30, 350, 200))
        self.BrainWidget.setObjectName("BrainWidget")
        self.treeView = QtWidgets.QTreeView(parent=ArcNeuroViz)
        self.treeView.setGeometry(QtCore.QRect(10, 30, 256, 681))
        self.treeView.setObjectName("treeView")
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ArcNeuroViz)
        QtCore.QMetaObject.connectSlotsByName(ArcNeuroViz)

    def retranslateUi(self, ArcNeuroViz):
        _translate = QtCore.QCoreApplication.translate
        ArcNeuroViz.setWindowTitle(_translate("ArcNeuroViz", "Arc NeuroWave Visualizer"))
        self.menuFile.setTitle(_translate("ArcNeuroViz", "File"))
        self.menuHelp.setTitle(_translate("ArcNeuroViz", "Help"))
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
