# Form implementation generated from reading ui file 'ui/NeuroVizMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArcNeuroViz(object):
    def setupUi(self, ArcNeuroViz):
        ArcNeuroViz.setObjectName("ArcNeuroViz")
        ArcNeuroViz.resize(960, 720)
        self.horizontalWidget = QtWidgets.QWidget(parent=ArcNeuroViz)
        self.horizontalWidget.setGeometry(QtCore.QRect(270, 180, 540, 360))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vtkWidget = QVTKRenderWindowInteractor(parent=self.horizontalWidget)
        self.vtkWidget.setEnabled(True)
        self.vtkWidget.setObjectName("vtkWidget")
        self.horizontalLayout.addWidget(self.vtkWidget)
        self.label = QtWidgets.QLabel(parent=ArcNeuroViz)
        self.label.setGeometry(QtCore.QRect(390, 80, 300, 60))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(ArcNeuroViz)
        QtCore.QMetaObject.connectSlotsByName(ArcNeuroViz)

    def retranslateUi(self, ArcNeuroViz):
        _translate = QtCore.QCoreApplication.translate
        ArcNeuroViz.setWindowTitle(_translate("ArcNeuroViz", "Form"))
        self.label.setText(_translate("ArcNeuroViz", "脑机接口可视化平台"))
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
