#! /bin/env python3
# Adrian Foy September 2023

"""Module to read Intan Technologies RHD2000 data file generated by
acquisition software (IntanRHX, or legacy Recording Controller / USB
Evaluation Board software).
"""
import time

from intanutil.header import (read_header,
                              header_to_result)
from intanutil.data import (calculate_data_size,
                            read_all_data_blocks,
                            check_end_of_file,
                            parse_data,
                            data_to_result)
from intanutil.filter import apply_notch_filter


def read_rhd_data(file_path):
    """Reads Intan Technologies RHD2000 data file generated by acquisition
    software (IntanRHX, or legacy Recording Controller / USB Evaluation
    board software).

    Data are returned in a dictionary, for future extensibility.
    """
    # Start measuring how long this read takes.
    tic = time.time()

    # Open file for reading.
    with open(file_path, 'rb') as fid:

        # Read header and summarize its contents to console.
        header = read_header(fid)

        # Calculate how much data is present and summarize to console.
        data_present, filesize, num_blocks, num_samples, rc_time, sam_rate = (
            calculate_data_size(header, file_path, fid))
        print('File contains {:0.3f} seconds of data.'.format(rc_time))
        print('Amplifiers were sampled at {:0.2f} kS/s.'.format(sam_rate / 1000))
        # If .rhd file contains data, read all present data blocks into 'data'
        # dict, and verify the amount of data read.
        if data_present:
            data = read_all_data_blocks(header, num_samples, num_blocks, fid)
            check_end_of_file(filesize, fid)

    # Save information in 'header' to 'result' dict.
    result = {}
    header_to_result(header, result)

    # If .rhd file contains data, parse data into readable forms and, if
    # necessary, apply the same notch filter that was active during recording.
    if data_present:
        parse_data(header, data)
        apply_notch_filter(header, data)

        # Save recorded data in 'data' to 'result' dict.
        data_to_result(header, data, result)

    # Otherwise (.rhd file is just a header for One File Per Signal Type or
    # One File Per Channel data formats, in which actual data is saved in
    # separate .dat files), just return data as an empty list.
    else:
        pass

    # Report how long read took.
    print('Done!  Elapsed time: {0:0.1f} seconds'.format(time.time() - tic))

    # Return 'result' dict.
    return result, rc_time, sam_rate


if __name__ == '__main__':
    a, record_time, sample_rate = read_rhd_data("../../s0633_0615_0690_221219_114735.rhd")

